version: '3'

services:
  frontend:
    image: alarm-front
    container_name: alarm-front
    build: ./
    command: 'npm run dev'
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
