version: '3'

services:
  frontend:
    image: alarm-front
    container_name: alarm-front
    build: ./
    command: 'yarn dev'
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - front-net

networks:
  front-net:
    driver: bridge
    name: alarm-front-net

