version: '3'

services:
  frontend:
    image: alarm-front
    container_name: alarm-front
    build: ./
    command: npm run dev
    restart: always
    env_file:
      - .env
    networks:
      - front-net
    ports:
      - 3000:3000
    volumes:
      - ./:/app

networks:
  front-net:
    driver: bridge
    name: alarm-front-net
