FROM node:lts as BUILDER

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .
RUN mv .envs/.cloud.env .env
RUN npm run build

FROM node:lts

WORKDIR /app


COPY --from=BUILDER /app/package.json .
COPY --from=BUILDER /app/.svelte-kit ./.svelte-kit/
COPY --from=BUILDER /app/vite.config.ts .
COPY --from=BUILDER /app/node_modules ./node_modules/

