version: '3'

services:
  previpago:
    image: alarm-front
    container_name: alarm-front
    build: ./
    command: 'npm run dev'
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
